Ledger API function for stake distribution and pool parameters query
input-output-hk/cardano-ledger-specs pull request #2511
Opened 2021-10-06 13:45 UTC by HeinrichApfelmus

### Issue Number

[CAD-3480](https://input-output.atlassian.net/browse/CAD-3480)

### Summary

module `Cardano.Ledger.Shelley.API.Wallet`:
* Introduce and export types `RewardParams` and `RewardInfoPool`
* The `getRewardInfoPools` function is essentially a refactoring of the `getNonMyopicMemberRewards` function.
* Also reorder the functions in the file and export list more thematically.

### Comments

Exporting `getRewardInfoPools` helps the wallet to calculate reward predictions (e.g. stake pool desirability, non-myopic rewards, but also future reward measures) for stake pools. It's intended to become a local state query in the node.

I have made a best effort to conform with the coding conventions in the ledger, but I'm probably off. I did not know where to put the types. Also, I did not know whether or how to write unit tests (though it seems that the old `GetRewardProvenance` does not have many tests either.)

2021-10-06 20:19 UTC, JaredCorduan approved these changes
Looks good to me! Thank you for leaving this module in better shape than you found it, much appreciated!

2021-10-11 07:15 UTC, nc6 requested changes
Code looks nice, but a few places where the comments need to be updated/clarified!

2021-10-11 07:15 UTC, nc6 commented on eras/shelley/impl/src/Cardano/Ledger/Shelley/API/Wallet.hs
> +-- | Get the /current/ registered stake pool parameters for a given set of
This haddock is incorrect!

2021-10-11 07:15 UTC, nc6 commented on eras/shelley/impl/src/Cardano/Ledger/Shelley/API/Wallet.hs
> +-- pools that are currently registered.
```suggestion
-- | Get the /current/ registered stake pools.
```

2021-10-11 07:15 UTC, nc6 commented on eras/shelley/impl/src/Cardano/Ledger/Shelley/API/Wallet.hs
> +-- see 'getRewardInfo'.
This function _is_ `getRewardInfo`...

2021-10-11 07:15 UTC, nc6 commented on eras/shelley/impl/src/Cardano/Ledger/Shelley/API/Wallet.hs
> +-- see 'getRewardInfo'.
Do you mean `getRewardInfoPools`? If so, I would say that the names are rather confusing! I'm guessing the intent is to deprecate this function in favour of the new one? If so, maybe we should name it accordingly.

2021-10-11 11:11 UTC, HeinrichApfelmus commented on eras/shelley/impl/src/Cardano/Ledger/Shelley/API/Wallet.hs
> +-- | Get the /current/ registered stake pool parameters for a given set of
Oops, sorry.

2021-10-11 11:24 UTC, HeinrichApfelmus commented on eras/shelley/impl/src/Cardano/Ledger/Shelley/API/Wallet.hs
> +-- see 'getRewardInfo'.
> Do you mean getRewardInfoPools? 

Yes, sorry.

```suggestion
-- see 'getRewardInfoPools'.
```

> If so, I would say that the names are rather confusing! I'm guessing the intent is to deprecate this function in favour of the new one? If so, maybe we should name it accordingly.

Well, the confusion that `getRewardInfo` returns a `RewardProvenance` is something that I inherited from the previous code 😅. But we can rename `getRewardInfo` to `getRewardProvenance` to disambiguate better. How would I (we) go about deprecation?

2021-10-11 13:12 UTC, nc6 approved these changes

2021-10-11 21:47 UTC, merged

2021-10-14 18:19 UTC, jackrousian commented
[CAD-3480]